-- 코드를 입력하세요
SELECT TITLE, B.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, 
   DATE_FORMAT (R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE

FROM USED_GOODS_BOARD AS B, USED_GOODS_REPLY AS R

WHERE 
    B.BOARD_ID = R.BOARD_ID
    AND
    B.CREATED_DATE LIKE '2022-10%' -- 이부분 B.인 것에 주의 해당기간 작성 '게시글'

ORDER BY CREATED_DATE, TITLE