-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE

FROM BOOK AS B, AUTHOR AS A
WHERE B.AUTHOR_ID = A.AUTHOR_ID
    AND
    CATEGORY = '경제'
ORDER BY 3;



